name: Test

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v2
        id: setup-rye
        with:
          enable-cache: true

      - name: Install
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: |
          rye config --set-bool behavior.use-uv=true
          rye sync --no-lock

      - name: Run tests
        run: rye run pytest --color=yes --cov --cov-report=xml --cov-report=term-missing

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
