name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"

      - name: Install rye
        uses: eifinger/setup-rye@v2

      - name: Install library
        run: rye sync

      - name: Run tests
        run: rye run pytest --cov=fpbase2 --cov-report=xml --cov-report=term-missing

      - uses: codecov/codecov-action@v3
